version: "3.8"
services:
    celery_beat:
        build: .
        command: python -m celery -A core beat
        networks:
            node_net:

    celery_worker:
        build: .
        command: python -m celery -A core worker -Q celery
        networks:
            node_net:
        depends_on:
            - celery_beat

    celery_worker_messaging:
        build: .
        command: python -m celery -A core worker -Q messaging
        networks:
            node_net:
        depends_on:
            - celery_beat

    celery_worker_trash:
        build: .
        command: python -m celery -A core worker -Q trash
        networks:
            node_net:
        depends_on:
            - celery_beat

    api:
        build: .
        environment:
            GRPC_PORT: "8000"
        ports:
            - "8000:8000"
        networks:
            node_net:
        depends_on:
          - celery_beat
          - celery_worker
          - celery_worker_messaging
          - celery_worker_trash

networks:
    node_net:
