[project]
name = "fyreplace-api"
version = "0.0.0"
description = "Fyreplace API"
authors = []
requires-python = ">=3.14,<3.15"
readme = "README.md"
license = "AGPL-3.0-or-later"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "black>=26,<27",
    "boto3>=1,<2",
    "celery[redis]>=5,<6",
    "django[argon2]>=5,<6",
    "django-anymail[mailgun]>=15,<16",
    "django-celery-beat>=2,<3",
    "django-extensions>=4,<5",
    "django-storages[boto3]>=1,<2",
    "django-stubs>=5,<6",
    "email-validator>=2,<3",
    "firebase-admin>=7,<8",
    "grpcio>=1,<2",
    "grpcio-tools>=1,<2",
    "grpc-interceptor>=0.15,<0.16",
    "httpx[http2]>=0.28,<0.29",
    "ipython>=9,<10",
    "isort>=8,<9",
    "mysqlclient>=2,<3",
    "pillow>=12,<13",
    "psycopg>=3,<4",
    "pyjwt[crypto]>=2,<3",
    "pytest-django>=4,<5",
    "pytest-xdist[psutil]>=3,<4",
    "python-dotenv>=1,<2",
    "python-magic>=0.4,<0.5",
    "qrcode>=8,<9",
    "rollbar>=1,<2",
    "tqdm>=4,<5",
    "uvicorn>=0.46,<0.47",
]
