apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  namespace: {{ include "fyreplace.name" . }}
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.contactEmail }}
    privateKeySecretRef:
      name: letsencrypt-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare
              key: token
