apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fyreplace-restart
  namespace: {{ include "fyreplace.name" . }}
rules:
  - apiGroups:
      - apps
      - extension
    resources:
      - deployments
    resourceNames:
      - {{ include "fyreplace.name" . }}
    verbs:
      - get
      - patch
