apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fyreplace-restart
  namespace: {{ include "fyreplace.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fyreplace-restart
subjects:
  - kind: ServiceAccount
    name: fyreplace-restart
    namespace: {{ include "fyreplace.name" . }}
