apiVersion: v1
kind: Service
metadata:
  namespace: {{ include "fyreplace.name" . }}
  name: {{ include "fyreplace.fullname" . }}
  labels:
    {{- include "fyreplace.labels" . | nindent 4 }}
    app: {{ include "fyreplace.fullname" . }}
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-name: {{ .Values.domain }}
    service.beta.kubernetes.io/do-loadbalancer-hostname: {{ .Values.domain }}
    service.beta.kubernetes.io/do-loadbalancer-tls-passthrough: "true"
    service.beta.kubernetes.io/do-loadbalancer-http2-ports: "50051"
    service.beta.kubernetes.io/do-loadbalancer-http-ports: "80"
    service.beta.kubernetes.io/do-loadbalancer-algorithm: "least_connections"
    service.beta.kubernetes.io/do-loadbalancer-enable-backend-keepalive: "true"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-port: "80"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-path: "/health/"
spec:
  type: LoadBalancer
  selector:
    {{- include "fyreplace.selectorLabels" . | nindent 4 }}
    app: {{ include "fyreplace.fullname" . }}
  ports:
    - name: rest
      port: 80
    - name: grpc
      port: 50051
