apiVersion: apps/v1
kind: Deployment
metadata:
  name: fyreplace
spec:
  selector:
    matchLabels:
      app: fyreplace
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: fyreplace
    spec:
      containers:
        - name: server-grpc
          image: ghcr.io/fyreplace/fyreplace-server:main
          imagePullPolicy: Always
          command: ['python', 'manage.py', 'grpc']
          envFrom:
            - configMapRef:
                name: environment
            - secretRef:
                name: vault
          env:
            - name: GRPC_PORT
              value: '50051'
          ports:
            - containerPort: 50051

        - name: server-rest
          image: ghcr.io/fyreplace/fyreplace-server:main
          imagePullPolicy: Always
          command: ['python', 'manage.py', 'runserver', '0.0.0.0:8080']
          envFrom:
            - configMapRef:
                name: environment
            - secretRef:
                name: vault
          ports:
            - containerPort: 8080

        - name: celery-beat
          image: ghcr.io/fyreplace/fyreplace-server:main
          imagePullPolicy: Always
          command: ['celery', '--app=core', 'beat', '--loglevel=info']
          envFrom:
            - configMapRef:
                name: environment
            - secretRef:
                name: vault

        - name: celery-worker
          image: ghcr.io/fyreplace/fyreplace-server:main
          imagePullPolicy: Always
          command: ['celery', '--app=core', 'worker', '--loglevel=info']
          envFrom:
            - configMapRef:
                name: environment
            - secretRef:
                name: vault

        - name: celery-worker-messaging
          image: ghcr.io/fyreplace/fyreplace-server:main
          imagePullPolicy: Always
          command: ['celery', '--app=core', 'worker', '--loglevel=info', '--queues=messaging']
          envFrom:
            - configMapRef:
                name: environment
            - secretRef:
                name: vault

        - name: celery-worker-trash
          image: ghcr.io/fyreplace/fyreplace-server:main
          imagePullPolicy: Always
          command: ['celery', '--app=core', 'worker', '--loglevel=info', '--queues=trash']
          envFrom:
            - configMapRef:
                name: environment
            - secretRef:
                name: vault

      initContainers:
        - name: migrations
          image: ghcr.io/fyreplace/fyreplace-server:main
          imagePullPolicy: Always
          command: ['python', 'manage.py', 'migrate']
          envFrom:
            - configMapRef:
                name: environment
            - secretRef:
                name: vault

        - name: static-files
          image: ghcr.io/fyreplace/fyreplace-server:main
          imagePullPolicy: Always
          command: ['python', 'manage.py', 'collectstatic', '--no-input']
          envFrom:
            - configMapRef:
                name: environment
            - secretRef:
                name: vault

---

apiVersion: v1
kind: Service
metadata:
  name: fyreplace
  labels:
    app: fyreplace
spec:
  type: LoadBalancer
  selector:
    app: fyreplace
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: http2
      port: 443
      targetPort: 50051
