name: Shipping

on:
  push:
    branches:
      - develop
    tags:
      - v*.*.*

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: true

      - name: Install Poetry
        run: python -m pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
          cache: poetry

      - name: Install dependencies
        run: poetry install --no-root

      - name: Compile protos
        run: make protobufs

      - name: Run tests
        run: poetry run python manage.py test
        env:
          SECRET_KEY: secret
          DATABASE_URL: postgres://postgres:postgres@localhost/postgres
