name: Shipping

on:
  push:
    branches:
      - main
      - develop
    tags:
      - v*.*.*

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install tools
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies
        run: python -m pip install --requirement requirements.txt

      - name: Compile protos
        run: make

      - name: Run tests
        run: python manage.py test
        env:
          SECRET_KEY: secret

  containers:
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags')

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deployment:
    needs: containers
    runs-on: ubuntu-latest
    environment: main
    if: startsWith(github.ref, 'refs/tags')

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set Kubernetes config
        working-directory: kubernetes
        run: 'echo $KUBE_CONFIG_B64 | base64 -d > kube.yml'
        env:
          KUBE_CONFIG_B64: ${{ secrets.KUBE_CONFIG_B64 }}

      - name: Create configuration
        working-directory: kubernetes
        run: |
          echo "S3_ACCESS_KEY_ID=${{ secrets.S3_ACCESS_KEY_ID }}" >> configuration.properties
          echo "S3_STORAGE_BUCKET_NAME=${{ secrets.S3_STORAGE_BUCKET_NAME }}" >> configuration.properties
          echo "S3_ENDPOINT_URL=${{ secrets.S3_ENDPOINT_URL }}" >> configuration.properties
          echo "S3_CUSTOM_DOMAIN=${{ secrets.S3_CUSTOM_DOMAIN }}" >> configuration.properties
          echo "MAILGUN_API_URL=${{ secrets.MAILGUN_API_URL }}" >> configuration.properties
          echo "DEFAULT_FROM_EMAIL=${{ secrets.DEFAULT_FROM_EMAIL }}" >> configuration.properties
          echo "SERVER_EMAIL=${{ secrets.SERVER_EMAIL }}" >> configuration.properties
          echo "ADMINS=${{ secrets.ADMINS }}" >> configuration.properties
          echo "EMAIL_LINKS_DOMAIN=${{ secrets.EMAIL_LINKS_DOMAIN }}" >> configuration.properties
          kubectl create configmap configuration --from-env-file=configuration.properties -o yaml --dry-run=client | kubectl --kubeconfig=kube.yml --namespace=fyreplace apply -f -

      - name: Create secrets
        working-directory: kubernetes
        run: |
          echo "ROLLBAR_TOKEN=${{ secrets.ROLLBAR_TOKEN }}" >> secrets.properties
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> secrets.properties
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> secrets.properties
          echo "CELERY_BROKER_URL=${{ secrets.CELERY_BROKER_URL }}" >> secrets.properties
          echo "S3_SECRET_ACCESS_KEY=${{ secrets.S3_SECRET_ACCESS_KEY }}" >> secrets.properties
          echo "MAILGUN_API_KEY=${{ secrets.MAILGUN_API_KEY }}" >> secrets.properties
          echo "MAILGUN_WEBHOOK_SIGNING_KEY=${{ secrets.MAILGUN_WEBHOOK_SIGNING_KEY }}" >> secrets.properties
          echo "MAILJET_API_KEY=${{ secrets.MAILJET_API_KEY }}" >> secrets.properties
          echo "MAILJET_SECRET_KEY=${{ secrets.MAILJET_SECRET_KEY }}" >> secrets.properties
          kubectl create secret generic secrets --from-env-file=secrets.properties -o yaml --dry-run=client | kubectl --kubeconfig=kube.yml --namespace=fyreplace apply -f -

      - name: Create DigitalOcean token
        working-directory: kubernetes
        run: |
          echo "token=${{ secrets.DO_API_TOKEN }}" >> digitalocean.properties
          kubectl create secret generic digitalocean --from-env-file=digitalocean.properties -o yaml --dry-run=client | kubectl --kubeconfig=kube.yml --namespace=fyreplace apply -f -

      - name: Deploy
        working-directory: kubernetes
        run: helm --kubeconfig=kube.yml upgrade --install --namespace=fyreplace fyreplace fyreplace
